Preview modified version of firefly
iquizoo/docs pull request #76
Opened 2018-12-26 01:52 UTC by SherrrryS

2018-12-26 04:00 UTC, psychelzh requested changes
More changes are required.

2018-12-26 04:00 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +每次需要追踪的萤火虫数目有5种可能（即3、4、5、6、7），不跟踪的萤火虫数目则始终为7个。
这句话要修改一下。改成自适应之后，需要追踪的萤火虫数目就有无穷多种可能性了。同时不追踪的萤火虫数目可以设置为需要追踪的萤火虫数目+2。

2018-12-26 04:00 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +每次需要追踪（发光的）萤火虫数目遵从1 up 2 down的规则，即做对一次发光萤火虫的个数即增加一个，做错两次下一次中发光萤火虫的个数减少一个
还需要说明做错一次不用减少。

2018-12-26 04:00 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +i）用户第n轮做对，n+1轮中发光萤火虫的个数变为x+1（5）；【1 up】
请使用Markdown的有序列表。例如：
```markdown
1. 第一条
1. 第二条
1. 第三条
```

不需要修改数字，全部用1即可。但是其实我觉得这个1 up 2 down他们都清楚，不用费心举例子了。

2018-12-26 04:00 UTC, SherrrryS commented on content/post/02102_firefly.Rmd
> +每次需要追踪的萤火虫数目有5种可能（即3、4、5、6、7），不跟踪的萤火虫数目则始终为7个。
see！+2会不会太少了？

2018-12-26 04:06 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +每次需要追踪的萤火虫数目有5种可能（即3、4、5、6、7），不跟踪的萤火虫数目则始终为7个。
那就+4？

2018-12-26 04:24 UTC, psychelzh commented
1. 不需要把正文变成有序列表。
1. 不同段落之间需要空一行。

2018-12-26 04:25 UTC, psychelzh requested changes
Please do some modifications accordingly.

2018-12-26 04:25 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +1.每次需要追踪的萤火虫数目n根据用户之前的成绩自适应，不追踪的萤火虫数目保持n+3。
我建议这第一段话可以不要了。直接整合在第二段里面去。

2018-12-26 04:25 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +例：第n轮中x个（4）发光萤火虫，
直接去掉这个例子吧。

2018-12-26 04:45 UTC, psychelzh requested changes
优化描述。

2018-12-26 04:45 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +* 例：第n轮中有x个（4）发光萤火虫
在正文中，`n`表示的是萤火虫数目，而这里`n`又表示第几轮。请统一一下。我个人觉得最好的办法是去掉字母，直接使用**数字**进行举例！

2018-12-26 11:26 UTC, psychelzh requested changes
Something needs modifying.

2018-12-26 11:26 UTC, psychelzh commented on content/post/02102_firefly.Rmd
> +* 例：第1轮中有3只发光萤火虫，即5只不发光萤火虫，总计8只
后面用到了试次，建议这里的轮次也改为试次吧。

2018-12-26 11:26 UTC, psychelzh commented on R/config/firefly/sdk.csv
> +`length`,`int array`,所有目标刺激的个数
这个说明可能不够明确。我觉得可以举一个例子了。

2018-12-27 12:02 UTC, psychelzh approved these changes

2018-12-27 12:03 UTC, closed without merging